#spring:
#  datasource:
#     url: jdbc:mysql://localhost:3306/productdb
#     username: root
#     password: Langat001@bett
#     driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    hibernate:
#      ddl-auto: update
#      show-sql: true
#  encryption:
#    salt:
#      rounds: 10
#  jwt:
#     algorithm:
#       key: SuperSecureSecretKey
#     issuer: eCommerce
# expiryInSeconds: 604800
#  mail:
#    host: localhost
#    port: 25


